import Head from "next/head";
import DashboardLayout from "@/layouts/dashboard/DashboardLayout";
import DashboardSection from "@/sections/dashboard/app";

DashboardPage.getLayout = (page) => <DashboardLayout>{page}</DashboardLayout>;

export default function DashboardPage() {
  return (
    <>
      <Head>
        <title>Touch Master</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <DashboardSection />
    </>
  );
}
